<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "напольные покрытия в #VS_CITY_1#");
$APPLICATION->SetPageProperty("description", "Продажа напольных покрытий . Выбрать и купить напольные покрытия в #VS_CITY_1# по самой привлекательной цене. Огромный выбор каталога с низкими ценами, фото и характеристиками в интернет-магазине ЭльХолл. Купить напольные покрытия в интернет-магазине с укладкой и доставкой по #VS_CITY_2#.");
$APPLICATION->SetPageProperty("title", "Каталог напольных покрытий: цены, отзывы, недорого - купить в интернет-магазине ЭльХолл - #VS_CITY#");
$APPLICATION->SetTitle("Каталог товаров - #VS_CITY#");?>

<?echo '<pre>'.print_r($_SESSION["VREGIONS_REGION"]["PRICE"],true).'</pre>';?>>

<?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	".default", 
	array(
		"PATH_TO_SHIPPING" => "/delivery/",
		"DISPLAY_IMG_WIDTH" => "178",
		"DISPLAY_IMG_HEIGHT" => "178",
		"DISPLAY_DETAIL_IMG_WIDTH" => "390",
		"DISPLAY_DETAIL_IMG_HEIGHT" => "390",
		"DISPLAY_MORE_PHOTO_WIDTH" => "86",
		"DISPLAY_MORE_PHOTO_HEIGHT" => "86",
		"SHARPEN" => "30",
		"AJAX_MODE" => "N",
		"SEF_MODE" => "Y",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "34",
		"USE_FILTER" => "Y",
		"USE_REVIEW" => "N",
		"USE_COMPARE" => "Y",
		"SHOW_TOP_ELEMENTS" => "N",
		"SECTION_COUNT_ELEMENTS" => "N",
		"SECTION_TOP_DEPTH" => "2",
		"PAGE_ELEMENT_COUNT" => "12",
		"LINE_ELEMENT_COUNT" => "1",
		"ELEMENT_SORT_FIELD" => "CATALOG_AVAILABLE",
		"ELEMENT_SORT_ORDER" => "desc",
		"ELEMENT_SORT_FIELD2" => "",
		"ELEMENT_SORT_ORDER2" => "",
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "CHASTOTA_H_H",
			2 => "MAX_KR_MOM",
			3 => "NAPRAJ_AKKUM",
			4 => "VES_S_AKKUM",
			5 => "",
		),
		"INCLUDE_SUBSECTIONS" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "Y",
		"LIST_META_KEYWORDS" => "UF_KEYWORDS",
		"LIST_META_DESCRIPTION" => "UF_META_DESCRIPTION",
		"LIST_BROWSER_TITLE" => "UF_BROWSER_TITLE",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "KLASS_IZNOSOSTOIKOSTI",
			1 => "ARTNUMBER",
			2 => "MANUFACTURER",
			3 => "COUNTRY",
			4 => "DLINA_MM",
			5 => "SHIRINA_MM",
			6 => "TOLSHINA_MM",
			7 => "V_RULONE_M_P",
			8 => "V_UPAKOVKE_M2",
			9 => "VES_VORSA",
			10 => "VORS",
			11 => "VISOTA_VORSA_MM",
			12 => "DIZAYN",
			13 => "DIZAYN_PARKETNOI_DOSKI",
			14 => "ZASHITNYI_SLOI_MM",
			15 => "ISPOLNENIE_PARKETA",
			16 => "KARTINKI",
			17 => "KLASS_GORYUCHESTI",
			18 => "KOL_VO_V_UPAKOVKE_SHT",
			19 => "MATERIAL_VORSA",
			20 => "MATERIAL_OSNOVI",
			21 => "NAZNAHENIE",
			22 => "OBRABOTKA_POVERHNOSTI",
			23 => "OSNOVA_LINOLEYMA",
			24 => "OTTENOK",
			25 => "POKRYTIE",
			26 => "PORODA_DEREVA_LAMINAT",
			27 => "PORODA_DEREVA_PARKET",
			28 => "RAZMER_KARAMOGRANITA_MM",
			29 => "SPOSOB_UKLADKI",
			30 => "TIP_VORSA",
			31 => "TIP_KERAMOGRANITA",
			32 => "TIP_KOVROLINA",
			33 => "TIP_LAMINATA",
			34 => "TIP_LINOLEYMA",
			35 => "TIP_MARMOLEUM",
			36 => "TIP_POVERHNOSTI",
			37 => "TIP_POVERHNOSTI_KERAMOGRANITA",
			38 => "FASKA",
			39 => "SHIRINA_M",
			40 => "KLASS_IZNOS",
			41 => "DISAIN_LAMINAT",
			42 => "design_floorboard",
			43 => "BLANKET_MM",
			44 => "ISPOLNENIE_SPARKETA",
			45 => "flammability_class",
			46 => "appointment_room",
			47 => "surface_treatment",
			48 => "basis_linoleuma",
			49 => "OTTENOK_LAMINATE",
			50 => "cover",
			51 => "PORODA_DEREVA",
			52 => "typeofwood",
			53 => "TYPE_OF_LAMINATE",
			54 => "TIP_POVERHNOSTI_LAMINAT",
			55 => "CHASTOTA_H_H",
			56 => "MAX_KR_MOM",
			57 => "NAPRAJ_AKKUM",
			58 => "VES_S_AKKUM",
			59 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "86400",
		"CACHE_NOTES" => "",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"PRICE_CODE" => array(
			0 => "Интернет-магазин (oblikdom.ru)",
			1 => "Интернет-магазин - Березники",
			2 => "Интернет-магазин - Екатеринбург",
			3 => "Интернет-магазин - Волгоград",
			4 => "Интернет-магазин - Ижевск",
			5 => "Интернет-магазин - Барнаул",
			6 => "Интернет-магазин - Воронеж",
			7 => "Интернет-магазин - Иркутск",
			8 => "Интернет-магазин - Дзержинск",
			9 => "Интернет-магазин - Йошкар-Ола",
			10 => "Интернет-магазин - Казань",
			11 => "Интернет-магазин - Каменск-Уральский",
			12 => "Интернет-магазин - Кемерово",
			13 => "Интернет-магазин - Киров",
			14 => "Интернет-магазин - Красноярск",
			15 => "Интернет-магазин - Курган",
			16 => "Интернет-магазин - Магнитогорск",
			17 => "Интернет-магазин - Миасс",
			18 => "Интернет-магазин - Набережные Челны",
			19 => "Интернет-магазин - Нефтекамск",
			20 => "Интернет-магазин - Нижневартовск",
			21 => "Интернет-магазин - Нижнекамск",
			22 => "Интернет-магазин - Нижний Новгород",
			23 => "Интернет-магазин - Нижний Тагил",
			24 => "Интернет-магазин - Новокузнецк",
			25 => "Интернет-магазин - Новосибирск",
			26 => "Интернет-магазин - Ноябрьск",
			27 => "Интернет-магазин - Омск",
			28 => "Интернет-магазин - Оренбург",
			29 => "Интернет-магазин - Орск",
			30 => "Интернет-магазин - Пермь",
			31 => "Интернет-магазин - Ростов-на-Дону",
			32 => "Интернет-магазин - Салават",
			33 => "Интернет-магазин - Стерлитамак",
			34 => "Интернет-магазин - Сургут",
			35 => "Интернет-магазин - Сыктывкар",
			36 => "Интернет-магазин - Тольятти",
			37 => "Интернет-магазин - Томск",
			38 => "Интернет-магазин - Тюмень",
			39 => "Интернет-магазин - Ульяновск",
			40 => "Интернет-магазин - Уфа",
			41 => "Интернет-магазин - Чебоксары",
			42 => "Интернет-магазин - Челябинск",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"USE_PRODUCT_QUANTITY" => "Y",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_ALSO_BUY" => "N",
		"USE_STORE" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"PAGER_TEMPLATE" => "arrows",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "DETAIL_PICTURE",
			3 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "NEWPRODUCT",
			1 => "SALELEADER",
			2 => "DISCOUNT",
			3 => "ARTNUMBER",
			4 => "MANUFACTURER",
			5 => "COUNTRY",
			6 => "CHASTOTA_H_H",
			7 => "MAX_KR_MOM",
			8 => "NAPRAJ_AKKUM",
			9 => "VES_S_AKKUM",
			10 => "",
		),
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "PROP2",
			3 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "PROP2",
			3 => "",
		),
		"LIST_OFFERS_LIMIT" => "",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "SHIRINA_M_TP",
			1 => "COLOR",
			2 => "PROP2",
			3 => "NAREZKA",
			4 => "",
		),
		"FILTER_NAME" => "arrFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PRICE_CODE" => array(
		),
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "Y",
		"USE_MIN_AMOUNT" => "N",
		"STORE_PATH" => "/store/#store_id#",
		"MAIN_TITLE" => "Наличие на складах",
		"HIDE_NOT_AVAILABLE" => "N",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"OFFERS_CART_PROPERTIES" => array(
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "asc",
		"IBLOCK_TYPE_REVIEWS" => "catalog",
		"IBLOCK_ID_REVIEWS" => "36",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"SEF_FOLDER" => "/catalog/",
		"USE_BIG_DATA" => "Y",
		"BIG_DATA_RCM_TYPE" => "any",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"STORES" => "",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SHOW_EMPTY_STORE" => "Y",
		"SHOW_GENERAL_STORE_INFORMATION" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"PROPERTY_CODE_MOD" => array(
			0 => "GUARANTEE",
			1 => "",
		),
		"BUTTON_PAYMENTS_HREF" => "/payments/",
		"BUTTON_CREDIT_HREF" => "/credit/",
		"BUTTON_DELIVERY_HREF" => "/delivery/",
		"SHOW_DEACTIVATED" => "N",
		"COMPONENT_TEMPLATE" => ".default",
		"SET_LAST_MODIFIED" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_SECTION" => "Y",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
		"TOP_ELEMENT_COUNT" => "9",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_ELEMENT_SORT_FIELD" => "sort",
		"TOP_ELEMENT_SORT_ORDER" => "asc",
		"TOP_ELEMENT_SORT_FIELD2" => "id",
		"TOP_ELEMENT_SORT_ORDER2" => "desc",
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_LIMIT" => "5",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"COMPATIBLE_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"compare" => "compare/",
			"smart_filter" => "#SECTION_CODE#/filter/#SMART_FILTER_PATH#/",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>